# Generated by Django 3.1.2 on 2020-10-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lap_times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDrivetrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TyreHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TyreMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TyreRadius',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TyreTreadwear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treadwear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TyreWidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='displacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.carenginedisplacement'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='sub_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.carsubmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TyreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.tyremake')),
            ],
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.tyreheight')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.tyremake')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.tyremodel')),
                ('radius', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.tyreradius')),
                ('treadwear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.tyretreadwear')),
                ('width', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.tyrewidth')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='drivetrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.cardrivetrain'),
        ),
    ]
