# Generated by Django 3.1.2 on 2020-10-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lap_times', '0003_event_eventname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sub_model',
            field=models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.carsubmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.CharField(blank=True, default='-', max_length=10, null=True),
        ),
    ]
