# Generated by Django 3.1.2 on 2020-10-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lap_times', '0005_auto_20201015_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.eventclass'),
        ),
        migrations.AddField(
            model_name='event',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.track'),
        ),
    ]
