# Generated by Django 3.1.2 on 2020-10-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lap_times', '0006_auto_20201015_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_time', models.DurationField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.driver')),
                ('event_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.eventclass')),
            ],
        ),
        migrations.AddField(
            model_name='eventname',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.track'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='tracktime',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap_times.eventname'),
        ),
    ]
