# Generated by Django 3.1.2 on 2020-10-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lap_times', '0007_auto_20201015_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktime',
            name='tyre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lap_times.tyre'),
        ),
    ]
